export const palabras = [
    'javascript', 
    'react', 'Boca juniors','Real Madrid',
    'programacion', 'desarrollo',
    'computadora',"Barcelona",
    'teclado',
    'monitor',"River plate",
    "argentina",
    "independiente","Godoy cruz",
    "Independiente Rivadavia",
    "san martin","gimnasia y esgrima de mendoza",
    "san lorenzo","rosario central",
    "tigre","banfield",
    "arsenal","newells",
    "colon","gimnasia",
    "huracan","velez",
    "elefante","murcielago",
    "avion",
    "tren","racing",
    "futbol",
    "pelicula","jazz",
    "guitarra","piano",
    "violin","saxofon",
    "trompeta", "flamenco",
    "cocodrilo",
    "hipopotamo", "jirafa",
    "camello","delfin",
    "burbuja","estrella",
    "planeta","cometa",
    "galaxia",
    "universo","constelacion",
    "astronauta",
    "cohete","saturno",
    "otorrinolaringólogo",
    "electroencefalografia","caleidoscopio",
    "inconstitucionalmente",
    "anticonstitucionalmente"
];